apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stockpilot.fullname" . }}-config
  labels:
    {{- include "stockpilot.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  DB_HOST: {{ include "stockpilot.fullname" . }}-postgres
  DB_PORT: {{ .Values.postgres.port | quote }}
  DB_NAME: {{ .Values.postgres.database | quote }}
