{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stockpilot.secretName" . }}
  labels:
    {{- include "stockpilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.auth.username | quote }}
  DB_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
